service: converter-on-lambda
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  profile: icosa_studios
  memorySize: 10240
  timeout: 900
  ecr:
    images:
      converter-container-image:
        path: ./

  iam:
    role:
      name: ConverterLambdaS3Access
      statements:
         # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::models.tabulasono.com/*'

functions:
  render:
    image:
      name: converter-container-image
    maximumRetryAttempts: 0
